#!/usr/bin/env bash

function _nomad_profile {
  local shome="${_nomad_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  nomad_VERSION="0.5.2"
}

_nomad_profile
