#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_nomad="$(nomad --version 2>/dev/null | awk '{print $2}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg nomad "$ver_nomad" '{nomad: $nomad}'
}

version "$@"
